server {
    listen 80;
    server_name _;

    location / {
        # 'flask-app'은 아래 compose 파일에서 정할 서비스 이름입니다.
        proxy_pass http://flask-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}